### ISSUE TITLE
Allow app registrations to be passed in as parameters

### ISSUE THREAD

**Issue by asanjabi** [Azure/reliable-web-app-pattern-dotnet#160]
Most customers that I've worked with don't have permission to create app registrations in their tenant and it must be done by an admin or a separate workflow.  Allowing them to create the registrations ahead of time would be extremely helpful.

**Comment by KSchlobohm** [comment]
Todo - remove secretOrRandom feature used in main.parameters.json as we do not want to build toward the assumption that the inputs come from key vault.

**Comment by KSchlobohm** [comment]
We should also be able to re-arrange the devOps workflow for QA of the project to support testing the website. Passing the app registration as a parameter in the pipeline should bypass the need to create an app registration (as a script run during azd postprovision outlined in #271) and deploy a working web app.

**Comment by KSchlobohm** [comment]
migrated to 1852595
