### ISSUE TITLE
Static Web Apps, Service Bus and APIM support?

### ISSUE THREAD

**Issue by ahmedsza** [Azure/reliable-web-app-pattern-dotnet#170]
Maybe consider adding Discussions on this GH repo? 

Just looked at this now. I like where this is heading.. A common pattern I see and also recommend is SPA, APIM and Service Bus, with B2C.. would this be a different pattern

When I saw reliable web app - i kinda half expected to see Service Bus.

**Comment by nishanil** [comment]
We are building the Service Bus, B2C, and APIM features into the Modern Web Apps pattern. Please work with us on the internal teams to gain access to our scoping and preview of MWA. We will close this issue now.
