### ISSUE TITLE
Generated user secrets have empty or invalid values.

### ISSUE THREAD

**Issue by asanjabi** [Azure/reliable-web-app-pattern-dotnet#181]
This causes a problem since user secrets override settings from app configuration.  Should either have accurate information or omit the values all together.

Relecloud.Web:
```code
"App:RelecloudApi:AttendeeScope": "",
"AzureAd:ClientId": "",
"AzureAd:ClientSecret": "1",
"AzureAd:TenantId": ""
```
Relecloud.Api
```code
"Api:AzureAd:ClientId": "",
"Api:AzureAd:TenantId": "",
```

**Comment by KSchlobohm** [comment]
@asanjabi this looks like the user secrets script was run before the createAppRegistrations.ps1 was run. is that what happened?
