### ISSUE TITLE
Review solution architecture with Azure teams to confirm architecture and delivery mechanism meets guidance.

### ISSUE THREAD

**Issue by rfrazier** [Azure/reliable-web-app-pattern-dotnet#22]
We should review the reference sample with other teams and incorporate their recommendations to ensure that we're providing the best possible guidance.

Topics to review:
* SQL Admin configuration and Password Generation
* Azure VNet configuration with respect to hybrid network recommendations

**Comment by KSchlobohm** [comment]
Met with teams
