### ISSUE TITLE
Modularize the bicep templates

### ISSUE THREAD

**Issue by rfrazier** [Azure/reliable-web-app-pattern-dotnet#28]
### Issue
All of the bicep resources are located in the resources.bicep file. It is becoming cumbersome to maintain and to understand conceptually. It should align with our operational excellence principles by splitting the deployment into discrete modules with names that align to their purpose.

### Todo
Separate the deployment into multiple bicep templates to improve maintainability.

### Progress
While working on the sql setup issue the team identified that key vault references (where the sql admin password is stored) must be passed via modules. [src](https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/key-vault-parameter?tabs=azure-cli#use-getsecret-function)

**Comment by KSchlobohm** [comment]
migrated to 1852537
