### ISSUE TITLE
createAppRegistrations scripts can't be run easily by admin

### ISSUE THREAD

**Issue by asanjabi** [Azure/reliable-web-app-pattern-dotnet#280]
**Describe the bug**
The createAppRegistration scripts use the IS_PROD flag from azd environment, this would mean anyone who is running the script needs to have azd and same environment setup on their system.  It would be better if it was passed in as a value, this way a user with not enough permissions can have an admin run the script for them.

**To Reproduce**

**Expected behavior**
Ability to easily have an admin run the script without having to have their environment configured.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [any]
 - Shell [PowerShell Core, Bash]
 - Shell Version [not applicable]
 - az version [not applicable]
    ``` 
**Additional context**
Add any other context about the problem here.

**Comment by KSchlobohm** [comment]
migrated to 1852568
