### ISSUE TITLE
Click the web service endpoint, page not found.

### ISSUE THREAD

**Issue by zedy-wj** [Azure/reliable-web-app-pattern-dotnet#282]
**Describe the issue:**
After `azd deploy`, click the endpoint of service web, you will get the error below:
![image](https://user-images.githubusercontent.com/81678720/229794983-45e24af3-29e1-4457-8732-e9aa376ac6b9.png)

**Repro Steps:**

1. azd init -t <template_name>
2. azd package
3. azd provision
4. Run command `azd deploy`, error below occurs, as one more empty resource group created when running the command `azd provision`. 
![image](https://user-images.githubusercontent.com/81678720/229795505-efdcba53-a995-49ba-b4cd-5d5b1d117541.png)
5. After specifying the resource group, run command `azd deploy`, click the endpoint of service web, you will get the error below:
![image](https://user-images.githubusercontent.com/81678720/229795701-b70783fc-38dc-4d02-9f39-02bcf9af9677.png)

**Environment:**
OS: Windows
Azd version: azd version 0.7.0-beta.2-pr.2672227 (commit dec4eb2c9f5932d3bd41f7e66b41c775c050ad48)

**Expected behavior:**
After deployment, the page can be opened normally.

@rajeshkamal5050, @KSchlobohm  for notification.

**Comment by KSchlobohm** [comment]
We can generate a default index html experience for the API to direct the experience to the right place. We can also adjust the SERVICES_WEB_ENDPOINT to use the front door URI. This should pair with #315

**Comment by KSchlobohm** [comment]
migrated to 1852507
