### ISSUE TITLE
[Feature Request] Include sample code/guidance to handle cache stampede/cache storm when concurrent requests miss the cache overwhelm the backend datastore

### ISSUE THREAD

**Issue by madhub** [Azure/reliable-web-app-pattern-dotnet#285]
**Is your feature request related to a problem? Please describe.**

Since this repo is to showcase pattern to build reliable web apps, it should provide **sample code/guidance** to handle **cache stampede/cache storm** when concurrent requests miss the cache, overwhelm the backend datastore. 
[My comment on the blog post](https://devblogs.microsoft.com/dotnet/introducing-the-reliable-web-app-pattern/#comment-17597)

**Describe the solution you'd like**
Provide **sample code/guidance** to handle **cache stampede/cache storm** when concurrent requests miss the cache, overwhelm the backend datastore. 

**Describe alternatives you've considered**

**Additional context**

**Comment by asanjabi** [comment]
Thank you for taking the time to provide us with your feedback, we value the input of our community and appreciate your thoughts.
We will be addressing this feedback and much deeper discussions of caching and performance in the next phase of the project where we are concentrating on performance and modernization.  For this phase we are focusing on migrating the application from on premises to Azure.
