### ISSUE TITLE
[Feature Request] Track transient exceptions and retries

### ISSUE THREAD

**Issue by RicardoNiepel** [Azure/reliable-web-app-pattern-dotnet#287]
**Feature Request:**
- Implement tracking of transient exceptions and retries if Azure SDK is used
- Implement tracking of transient exceptions, retries and circuit breaker if Polly is used

**Context**
According to the [WAF Reliability Pillar](https://learn.microsoft.com/en-us/azure/architecture/framework/resiliency/monitor-best-practices#track-transient-exceptions-and-retries) **transient exceptions, retries and circuit breakers should be monitored**.

I cannot see how this is currently implemented with the Azure SDK built-in retries and with the usage of Polly.

**Comment by KSchlobohm** [comment]
migrated to 1852563

**Comment by RicardoNiepel** [comment]
@KSchlobohm @nishanil can you pls explain why it was closed/set to done? I cannot find the implementation for this.
