### ISSUE TITLE
Describe Azure subscription requirements

### ISSUE THREAD

**Issue by KSchlobohm** [Azure/reliable-web-app-pattern-dotnet#288]
## Todo
1. Update the pre-requisites of the guide to describe the azure RBAC required to provision (User Access Administrator, and Contributor)

**Comment by asanjabi** [comment]
I believe "Role Based Access Control Administrator" role would be enough instead of "User Access Administrator", it is in preview now.

**Comment by KSchlobohm** [comment]
> I believe "Role Based Access Control Administrator" role would be enough instead of "User Access Administrator", it is in preview now.

Good to know! We can give it a test with our pipeline.
