### ISSUE TITLE
web app must be restarted to detect configuration changes

### ISSUE THREAD

**Issue by rfrazier** [Azure/reliable-web-app-pattern-dotnet#29]
### Issue
It would be a better demonstration of operational excellence if the web app could detect or "pick up" changes from App Configuration Service or Key Vault without an App Pool restart.

### Todo
- Research whether this is a code change or a feature change.
- Modify the code
- Modify the guide to describe this feature and to explain what's happening when simulating faults

**Comment by KSchlobohm** [comment]
relates to #234
