### ISSUE TITLE
When creating a single region deployment, an empty env-secondary-rg is created

### ISSUE THREAD

**Issue by adrianhall** [Azure/reliable-web-app-pattern-dotnet#296]
**Describe the bug**
When creating a single region deployment, an empty `$myEnvironmentName-secondary-rg` resource group is created, with a default location of the primary location.

**To Reproduce**
1. Do not `azd set env SECONDARY_AZURE_LOCATION`
2. Run azd deploy
3. Note the creation of the secondary resource group and it's default location.

**Expected behavior**
The `$myEnvironmentName-secondary-rg` should not be created.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Shell: PowerShell Core
 - Shell Version: PowerShell 7.3.4
 - az version 
```json 
{
  "azure-cli": "2.45.0",
  "azure-cli-core": "2.45.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "account": "0.2.5",
    "init": "0.1.0"
  }
}
```
 - az bicep version `Bicep CLI version 0.16.2 (de7fdd2b33)`
 - azd version `azd version 0.8.0-beta.2 (commit 429b6ccf9a9d1616efa8988f2f8561deeb464c71)`
 - dotnet --version `7.0.203`

**Comment by KSchlobohm** [comment]
We created this experience due to the bug https://github.com/Azure/azure-dev/issues/553

Based on our conditional deployments the name of our secondary resource group was being sent to Azure where the AZD tool was retrieving the name and failing during azd teardown due to the group not being created.

**Comment by KSchlobohm** [comment]
migrated to 1864725
