### ISSUE TITLE
turn on SQL audit logs

### ISSUE THREAD

**Issue by rfrazier** [Azure/reliable-web-app-pattern-dotnet#30]
### Issue
These settings should be enabled

![Image](https://user-images.githubusercontent.com/23503973/184250200-3bf5fcc9-ae14-4df3-95cd-7b37ce3f2626.png)

https://docs.microsoft.com/en-us/azure/azure-sql/database/auditing-overview?view=azuresql

## Progress
looks like this may be something we can enable via bicep
https://docs.microsoft.com/en-us/azure/templates/microsoft.sql/servers/auditingsettings?pivots=deployment-language-bicep

reviewed the existing dotnet sample - does not demonstrate this feature
https://github.com/microsoft/App-Templates

**Comment by KSchlobohm** [comment]
Can look at fieldengineer.net

**Comment by KSchlobohm** [comment]
migrated to 1852598
