### ISSUE TITLE
"Find additional resources" link in reliable-web-app-pattern readme returns 404

### ISSUE THREAD

**Issue by gbowerman** [Azure/reliable-web-app-pattern-dotnet#303]
**Describe the bug**
The main readme for reliable web app pattern readme has a "Find additional resources" link near the end of the page. It lniks to https://github.com/Azure/reliable-web-app-pattern-dotnet/blob/main/additional-resources.md which returns a 404.

**To Reproduce**
1. Go to https://github.com/Azure/reliable-web-app-pattern-dotnet/blob/main/README.md
2. Scroll to the bottom
3. Click on the "Find additional resources" link

**Comment by KSchlobohm** [comment]
looks like this content was lost as we rearranged and published to Azure Architecture Center - https://github.com/Azure/reliable-web-app-pattern-dotnet/pull/256/files#diff-1fbea232d688ef97fcf1bff3d3a867fbb241e86fcf5e1b9fefa79cc53126ea82

**Comment by KSchlobohm** [comment]
migrated to 1852540
