### ISSUE TITLE
createAppRegistrations.ps1 does not add required permissions to frontend app registration

### ISSUE THREAD

**Issue by adrianhall** [Azure/reliable-web-app-pattern-dotnet#308]
**Describe the bug**
After running createAppRegistrations.ps1, the `-frontend` app registration has no permissions.  Permission for the `-api` exposed scope is required.

**Expected behavior**
The `-frontend` app registration should have permission to the scope exposed by the `-api` app registration.

**Screenshots**
![image](https://github.com/Azure/reliable-web-app-pattern-dotnet/assets/1489465/3b121a49-b1f4-4c02-b82d-cc349b2acffd)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Shell: Powershell
 - Shell Version: 7.3.4
 - az version [e.g.]
    ``` 
        {
          "azure-cli": "2.48.1",
          "azure-cli-core": "2.48.1",
          "azure-cli-telemetry": "1.0.8",
          "extensions": {}
        }
    ```
 - az bicep version: Bicep CLI version 0.17.1 (d423d61882)
 - azd version: azd version 0.8.0-beta.2 (commit 429b6ccf9a9d1616efa8988f2f8561deeb464c71)
 - dotnet --version: 7.0.203

**Additional context**
Deployed in Microsoft tenant.

**Comment by KSchlobohm** [comment]
Pairs with #307

**Comment by KSchlobohm** [comment]
At the end:
1. the scope should be consent by UsersAndAdmin
1. remove preAuthorized client
1. pass-through scope from API to front-end so a user can consent
1. front-end web app should have API permission to call back-end api web app

**Comment by KSchlobohm** [comment]
migrated to 1852505
