### ISSUE TITLE
Document and describe regional failover process

### ISSUE THREAD

**Issue by KSchlobohm** [Azure/reliable-web-app-pattern-dotnet#323]
The solution deploys code to two regions but does not have a failover event/trigger to migrate traffic and data to the second region.

We need to document the approach for migrating from one region to the second region detailing the responsibilities and the processes which would be manually performed. We should be able to leverage some of the same approaches and features used for java RWA.

**Comment by KSchlobohm** [comment]
migrated to 1852450

**Comment by GlibMartynenko** [comment]
Hi @KSchlobohm, Could you please describe what does it mean "migrated to 1852450"? I'm looking for a solution to have data replication between two regions. As I understand, we need to enable SQL Geo Replica and the Storage account type should be GRS.

**Comment by KSchlobohm** [comment]
Hi @GlibMartynenko the "migrated to" pertains to one of our backlog grooming activities.

As for the content, it sounds like this reference in the Java RWA implementation may be helpful as a starting point for the topics you're considering: https://github.com/Azure/reliable-web-app-pattern-java/blob/main/plan.md

You may also be interested in: https://learn.microsoft.com/en-us/azure/azure-sql/database/active-geo-replication-overview?view=azuresql-db
