### ISSUE TITLE
What does 'rc' signify?

### ISSUE THREAD

**Issue by TWolversonReply** [Azure/reliable-web-app-pattern-dotnet#328]
The Key Vault definition names the Key Vault **rc-{resourceToken}-kv**. What is 'rc' meant to stand for? I can accept that these templates have to adopt a naming convention that might be different to that expected by one's own policies - although ideally azd would support an abstraction for defining resource naming conventions across the solution that minimises repetition - but in most cases apart from this one, what they are trying to convey is obvious. Full search for 'rc-' doesn't surface any explanation.

**Comment by TWolversonReply** [comment]
Ah, I suspect it might be Relecloud, the example organisation.

**Comment by KSchlobohm** [comment]
Sorry for the delayed reply. You are correct the rc prefix is intended to represent Relecloud for this sample.

An approach we are considering as we proceed is to use CAF based prefix naming as demonstrated in the azd tooling. You can see examples in their naming file here: https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/abbreviations.json
