### ISSUE TITLE
Updating/work-with this template for GHA and Azd Devcontainer feature.

### ISSUE THREAD

**Issue by zedy-wj** [Azure/reliable-web-app-pattern-dotnet#329]
We are updating this template to support new features in `Github Action` and `Azd Devcontainer`.

1. For the Github Action feature: We will remove two lines of code on container image and add GHA code after checkout step in the `.github/workflow/azure-dev.yml` file. (Shown as below)
<img width="302" alt="image" src="https://github.com/Azure-Samples/openai-plugin-fastapi/assets/81678720/b78e7045-08c4-4e09-90cd-ba0b22f50fe7">

2. For the Azd Devcontainer feature: 

- Add  the following code in `devcontainer.json` file.

``` 
"ghcr.io/azure/azure-dev/azd:latest": {}
``` 

 and remove the relevant code for installing azd in `devcontainer.json` file.

```
"postCreateCommand": "curl -fsSL https://aka.ms/install-azd.sh | bash",
```
- Remove the relevant code for build Dockerfile in `devcontainer.json` file and remove `Dockerfile` under `.devcontainer` folder.

```
"build": {
	"dockerfile": "Dockerfile",
	"args": { 
		"VARIANT": "6.0-bullseye"
	}		
},
```

and add an `image` in `devcontainer.json` file.
```
"image": "mcr.microsoft.com/vscode/devcontainers/dotnet:0-6.0-bullseye",
```

@rajeshkamal5050 , @KSchlobohm , @nishanil for notification.

**Comment by KSchlobohm** [comment]
Thanks for the feedback @zedy-wj we've updated the content to support Dev Containers and a newer version of AZD in the latest PR #369.
