### ISSUE TITLE
BadRequest: Azure subscription is not registered with CDN Provider.

### ISSUE THREAD

**Issue by mcp-net** [Azure/reliable-web-app-pattern-dotnet#335]
running "azd provision" getting error:

ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
BadRequest: Azure subscription is not registered with CDN Provider.

If this is MANDATORY, why is not part of script?

**Comment by adrianhall** [comment]
Great point - this is generally a "really-one-time" thing per subscription, so we don't bump into it.  Note that adding a registration for something already registered is an error.  So I will update the known-issues.md with the relevant information and close this once the PR is merged.
