### ISSUE TITLE
Provide guidance on how to fit the solution into a typical enterprise's Azure Deployment

### ISSUE THREAD

**Issue by jeffvan98** [Azure/reliable-web-app-pattern-dotnet#61]
Typical enterprise customers build virtual data center in the cloud.  These data centers are comprised of hub-and-spoke networks that facilitate security and control over the virtual data center. Enterprise applications, such as the one described here, must exist within the context of this virtual data center.  Please provide guidance on how this application pattern can fit into the virtual data center.

**Comment by KSchlobohm** [comment]
closed as LZA integration will be considered as part of design work moving forward.
