### ISSUE TITLE
Fix risk alerts and update docs

### ISSUE THREAD

**Issue by nishanil** [Azure/reliable-web-app-pattern-dotnet#85]
![risk](https://user-images.githubusercontent.com/3107766/193053794-65996782-34e3-4cb7-9e4d-5dfc1f87f35a.png)

- update docs to describe availability features per environment (cost management section)
- deploy prod scenario, identify critical availability issues and address
- enable auto heal
- enable health check endpoints
- as needed, change minimum horizontal instance count to 2 instances

**Comment by KSchlobohm** [comment]
closed in reference to resiliency report
