### ISSUE TITLE
Getting Auth errors when trying to debug locally in Visual Studio

### ISSUE THREAD

**Issue by hannesne** [Azure/reliable-web-app-pattern-dotnet#98]
Seems to be having trouble getting the required secrets when starting up the web project:

![image](https://user-images.githubusercontent.com/11169376/196296023-8fa320a8-c847-4f19-9c53-ce695142e6b6.png)

I've setup the values in the secret.json file:

![image](https://user-images.githubusercontent.com/11169376/196296237-4e73c546-cf83-44d9-83ce-3a668bc0e3db.png)

Here's teh detail of the exception message: Service request failed.
Status: 403 (Forbidden)

Headers:
Server: openresty/1.17.8.2
Date: Mon, 17 Oct 2022 22:31:57 GMT
Connection: keep-alive
x-ms-request-id: 372708e0-bbaa-47a4-b929-e459b979f929
x-ms-client-request-id: bfddf1af-1310-4b6d-88ec-e4414c0d11e1
x-ms-correlation-request-id: 372708e0-bbaa-47a4-b929-e459b979f929
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: REDACTED
Strict-Transport-Security: max-age=15724800; includeSubDomains
Content-Length: 0

I've checked the role assignments in the portal, and my user has been assigned the expected role on app config:

![image](https://user-images.githubusercontent.com/11169376/196297021-ea4ae89e-4c7e-45d7-898c-7efbe834a8c2.png)

And also on both keyvaults.

**Comment by iarunpaul** [comment]
it seems you are loging in to the wrong tenant.
In the case you can try to provide the tenant id as options here.
```
    var options = new VisualStudioCredentialOptions
    {
        TenantId = "your-tenant-id"
    };
    tokenCredential = new ChainedTokenCredential(new VisualStudioCredential(options), new VisualStudioCodeCredential(), new AzureCliCredential());
```
Here you chain the token calls, but you specify the tenant in Vs credntial call.
